package com.cyber.vistas;
import com.cyber.controladores.ClienteControlador;
import com.cyber.modelos.Cliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * Vista principal para la gestión de clientes.
 * Implementada con Swing, permite realizar operaciones CRUD
 * (Crear, Leer, Actualizar, Eliminar) sobre la tabla clientes.
 */

public class ClienteVista extends javax.swing.JFrame {
    
    // Logger para registrar errores en la interfaz
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteVista.class.getName());

    
    private ClienteControlador controlador;   // Controlador que conecta la vista con la lógica de negocio
    private int idClienteSeleccionado = -1;  // ID del cliente seleccionado en la tabla
    
    
     /**
     * Constructor: inicializa componentes y carga la tabla
     */
        public ClienteVista() {
        initComponents();

        controlador = new ClienteControlador();
        cargarTabla();
        }
    
    
     /**
     * Método para cargar todos los clientes en la tabla
     */
     private void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);

        List<Cliente> clientes = controlador.listarClientes();

        for (Cliente cliente : clientes) {
            modelo.addRow(new Object[]{
                cliente.getIdCliente(),
                cliente.getNombre(),
                cliente.getDni(),
                cliente.getTelefono()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("GESTIÓN DE CLIENTES");

        lblNombre.setText("Nombre:");

        lblDni.setText("DNI:");

        jLabel1.setText("Teléfono:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "DNI", "Teléfono"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jLabel2.setText("Clientes Registrados:");

        lblBuscar.setText("Buscar cliente por DNI:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnMenu.setText("Volver al Menú Principal");
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombre)
                                        .addComponent(lblDni))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombre)
                                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBuscar)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnMenu))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
      // ------------------- EVENTOS DE BOTONES -------------------
    
    //Acción del botón Eliminar:   
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         if (idClienteSeleccionado == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente.");
            return;
        }

        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar el cliente seleccionado?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            boolean eliminado = controlador.eliminarCliente(idClienteSeleccionado);

            if (eliminado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.");
                cargarTabla();
                txtNombre.setText("");
                txtDni.setText("");
                txtTelefono.setText("");
                idClienteSeleccionado = -1;
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar el cliente.");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
    
    //Acción del botón Guardar
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = txtNombre.getText().trim();
        String dni = txtDni.getText().trim();
        String telefono = txtTelefono.getText().trim();

        // Validaciones básicas
        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un nombre.");
            return;
        }
        if (dni.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un DNI.");
            return;
        }
        if (!dni.matches("\\d{8}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El DNI debe tener exactamente 8 dígitos.");
            return;
        }
        if (controlador.existeDni(dni)) {
            javax.swing.JOptionPane.showMessageDialog(
            this,
            "Ya existe un cliente con ese DNI.");
            return;
        }
        
        if (telefono.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un teléfono.");
            return;
        }
        if (!telefono.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El teléfono solo puede contener números.");
            return;
        }
        if (telefono.length() < 10) { //Validar longitud mínima del teléfono
            javax.swing.JOptionPane.showMessageDialog(this, "El teléfono debe tener al menos 10 dígitos.");
            return;
        }
        if (telefono.length() > 12) { ////Validar longitud manima del teléfono
        javax.swing.JOptionPane.showMessageDialog(this, "El teléfono no puede tener más de 12 dígitos.");
            return;
        }

        // Guardar cliente
        boolean guardado = controlador.guardarCliente(nombre, dni, telefono);

        if (guardado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente guardado correctamente.");
            cargarTabla();
            txtNombre.setText("");
            txtDni.setText("");
            txtTelefono.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo guardar el cliente.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    //Acción al hacer clic en la tabla (selección de cliente)
    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        int fila = tblClientes.getSelectedRow();

        if (fila != -1) {

         idClienteSeleccionado =
            Integer.parseInt(
                    tblClientes.getValueAt(fila, 0).toString()
            );

         txtNombre.setText(
            tblClientes.getValueAt(fila, 1).toString()
         );

        txtDni.setText(
            tblClientes.getValueAt(fila, 2).toString()
         );

        txtTelefono.setText(
            tblClientes.getValueAt(fila, 3).toString()
    );
}
    }//GEN-LAST:event_tblClientesMouseClicked
    
    
    //Acción del botón Modificar
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         if (idClienteSeleccionado == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla.");
            return;
        }

        String nombre = txtNombre.getText().trim();
        String dni = txtDni.getText().trim();
        String telefono = txtTelefono.getText().trim();

        boolean modificado = controlador.modificarCliente(idClienteSeleccionado, nombre, dni, telefono);

        if (modificado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente modificado correctamente.");
            cargarTabla();
            txtNombre.setText("");
            txtDni.setText("");
            txtTelefono.setText("");
            idClienteSeleccionado = -1;
            tblClientes.clearSelection();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo modificar el cliente.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    //Acción del botón Limpiar
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNombre.setText("");
        txtDni.setText("");
        txtTelefono.setText("");
        idClienteSeleccionado = -1;
        tblClientes.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    
    //Acción del botón Buscar
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String dni = txtBuscar.getText().trim();
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);

        if (dni.isEmpty()) {
            cargarTabla();
            return;
        }

        List<Cliente> clientes = controlador.buscarPorDni(dni);

        for (Cliente cliente : clientes) {
            modelo.addRow(new Object[]{
                cliente.getIdCliente(),
                cliente.getNombre(),
                cliente.getDni(),
                cliente.getTelefono()
            });
        }
        
        if (clientes.isEmpty()) { //Mostrar mensaje si la búsqueda no encuentra resultados
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "No se encontraron clientes con ese DNI.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    //Botón que te lleva al menú principal de la aplicación
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        menu ventanaMenu = new menu();
        ventanaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteVista().setVisible(true));
    }

    
    
       // ------------------- VARIABLES DE LA INTERFAZ -------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
