package com.cyber.vistas;

import com.cyber.controladores.SesionControlador;
import javax.swing.ListSelectionModel;

public class SesionVista
    extends javax.swing.JFrame
{
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SesionVista.class.getName());
    
    private SesionControlador controlador;
    
    public SesionVista()
    {
        initComponents();
        this.jTable1.setRowSelectionAllowed(true);
        this.jTable1.setColumnSelectionAllowed(false);
        this.jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.controlador = new SesionControlador();
        this.controlador.actualizarTabla(this.jTable1);
        cargarClientes();
        cargarPCDisponibles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 500));

        jPanel1.setMinimumSize(new java.awt.Dimension(560, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Clientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("PCs Libres");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButton1.setText("Iniciar Sesion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 110, -1));

        jButton2.setText("Finalizar Sesion");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Sesión", "ID Cliente", "Cliente", "PC", "Inicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 570, 320));

        jButton3.setText("Agregar Consumos");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jComboBox1.getSelectedItem() == null)
        {
            System.out.println("Seleccione un cliente");
            return;
        }

        if (jComboBox2.getSelectedItem() == null)
        {
            System.out.println("Seleccione una computadora");
            return;
        }
        String nombreSeleccionado = this.jComboBox1.getSelectedItem().toString();
        String pcSeleccionada = this.jComboBox2.getSelectedItem().toString();

        int idCliente = this.controlador.obtenerIDPorNombre(nombreSeleccionado);
        int numero_pc = Integer.parseInt(pcSeleccionada);

        this.controlador.iniciarSesion(idCliente, numero_pc, this.jTable1);
        
        this.jComboBox1.removeAllItems();
        this.jComboBox2.removeAllItems();
        
        cargarClientes();
        cargarPCDisponibles();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.controlador.finalizarSesion(this.jTable1, this.jComboBox1, this.jComboBox2);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int fila = this.jTable1.getSelectedRow();

        if(fila == -1)
        {
            System.out.println("Seleccione una sesión");
            return;
        }

        int idSesion = Integer.parseInt(this.jTable1.getValueAt(fila, 0).toString());
        
        String producto =javax.swing.JOptionPane.showInputDialog(this,"Ingrese el ID del Producto:");

        if(producto == null)
        {
            return;
        }

        String cantidad =javax.swing.JOptionPane.showInputDialog(this,"Ingrese la cantidad:");

        if(cantidad == null)
        {
            return;
        }

        int idProducto = Integer.parseInt(producto);
        int cant = Integer.parseInt(cantidad);

        //ConsumoControlador cc = new ConsumoControlador();

        //cc.agregarConsumo(idSesion, idProducto, cant);

        javax.swing.JOptionPane.showMessageDialog(this,"Consumo agregado correctamente");
    }//GEN-LAST:event_jButton3MouseClicked

    private void cargarClientes()
    {
        this.jComboBox1.removeAllItems();
        for (int i = 0; i < this.controlador.cargarClientes().size(); i++)
        {
            this.jComboBox1.addItem(this.controlador.cargarClientes().get(i));
        }
    }
    
    private void cargarPCDisponibles()
    {
        this.jComboBox2.removeAllItems();
        
        for (int i = 0; i < this.controlador.cargarPCDisponibles().size(); i++)
        {
            this.jComboBox2.addItem("" + this.controlador.cargarPCDisponibles().get(i));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void mainSesion() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SesionVista().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
